services:
    app:
        build: 
            context: "."
        security_opt:
            - seccomp:unconfined
        ports:
        - "3000:3000"
        environment:
            - POSTGRES_HOST=host.docker.internal
            - REDIS_HOST=redis
            - REDIS_PORT=6379
        env_file: 
            - .env
        depends_on:
            - redis

    redis:
        image: "redis:latest"
        ports:
          - "6379:6379"
